### ISSUE TITLE
Change the build system used  (CMake -> Meson)

### ISSUE THREAD

**Issue by rafaelcn** [rafaelcn/Kokiri#2]
CMake is quite complex and error prone by design, we should change to something better that can be easily written and also is a multi-platform build system. Our picked choice is *meson* and the following tasks should be complete:

- [x] Substitute the old build system with a meson one (on another branch and then merge it).
- [x] Create unit tests within the build system to assure the modules created on the framework.
- [x] Change the README.md accordingly with the new build system.

**Comment by waruqi** [comment]
Also consider using other build systems, such as: https://github.com/tboox/xmake 😄
